# Generated by Django 6.0.3 on 2026-03-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('colors', models.JSONField(help_text='3x3 face colors')),
            ],
        ),
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_collaborative', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MosaicCube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube_prep.cube')),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosaiccubes', to='cube_prep.mosaic')),
            ],
            options={
                'unique_together': {('mosaic', 'row', 'col')},
            },
        ),
    ]
