# Generated by Django 6.0.3 on 2026-03-20 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuber',
            fields=[
                ('cuber_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('adjective', models.CharField(max_length=50)),
                ('superhero', models.CharField(max_length=50)),
                ('color_code_hash', models.CharField(max_length=128)),
                ('avatar_variant', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_active_date', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuber_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Enseignant'), ('coach', 'Entraîneur'), ('club_leader', 'Animateur de Club'), ('parent', 'Parent Responsable')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('group_code', models.CharField(max_length=6, unique=True)),
                ('group_type', models.CharField(choices=[('class', 'Classe'), ('club', 'Club'), ('team', 'Équipe'), ('practice', 'Groupe de Pratique')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('leaders', models.ManyToManyField(related_name='groups', to='cubing_users.leader')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20)),
                ('cuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubing_users.cuber')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubing_users.group')),
            ],
            options={
                'unique_together': {('cuber', 'group')},
            },
        ),
    ]
