# Generated by Django 6.0.3 on 2026-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='first_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du prénom (ex: 'TO' pour Tommy)", max_length=2),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='last_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du nom de famille (ex: 'SM' pour Smith)", max_length=2),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nom complet ou surnom (visible seulement par le leader)', max_length=100),
        ),
    ]
