# Generated by Django 6.0.3 on 2026-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0002_groupmembership_first_name_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='nickname',
        ),
        migrations.AddField(
            model_name='cuber',
            name='first_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du prénom (ex: 'TO' pour Tommy)", max_length=2),
        ),
        migrations.AddField(
            model_name='cuber',
            name='last_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du nom de famille (ex: 'SM' pour Smith)", max_length=2),
        ),
    ]
