# Generated by Django 6.0.3 on 2026-03-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0003_remove_groupmembership_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuber',
            name='avatar_variant',
        ),
    ]
