# Generated by Django 6.0.3 on 2026-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0004_remove_cuber_avatar_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuber',
            options={'verbose_name': 'Cubeur', 'verbose_name_plural': 'Cubeurs'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': 'Adhésion au groupe', 'verbose_name_plural': 'Adhésions aux groupes'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': 'Leader', 'verbose_name_plural': 'Leaders'},
        ),
        migrations.RemoveField(
            model_name='cuber',
            name='adjective',
        ),
        migrations.RemoveField(
            model_name='cuber',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cuber',
            name='superhero',
        ),
        migrations.AddField(
            model_name='cuber',
            name='animal',
            field=models.CharField(choices=[('renard', 'Renard'), ('hibou', 'Hibou'), ('panda', 'Panda'), ('tortue', 'Tortue'), ('grenouille', 'Grenouille'), ('lapin', 'Lapin'), ('ours', 'Ours'), ('castor', 'Castor'), ('loup', 'Loup'), ('manchot', 'Manchot'), ('ecureuil', 'Écureuil'), ('perroquet', 'Perroquet')], default='hibou', help_text="Animal choisi par l'élève à l'inscription (1 parmi 12)", max_length=20),
        ),
        migrations.AddField(
            model_name='cuber',
            name='cube_color',
            field=models.CharField(choices=[('rouge', 'Rouge'), ('orange', 'Orange'), ('jaune', 'Jaune'), ('vert', 'Vert'), ('bleu', 'Bleu'), ('blanc', 'Blanc')], default='bleu', help_text="Couleur du foulard — les 6 couleurs officielles du Rubik's Cube", max_length=10),
        ),
        migrations.AddField(
            model_name='cuber',
            name='quality_1',
            field=models.CharField(choices=[('curieux', 'Curieux·se'), ('intelligent', 'Intelligent·e'), ('rapide', 'Rapide'), ('determine', 'Déterminé·e'), ('perseverant', 'Persévérant·e'), ('concentre', 'Concentré·e'), ('gentil', 'Gentil·le'), ('aidant', 'Aidant·e'), ('creatif', 'Créatif·ve'), ('joyeux', 'Joyeux·se'), ('patient', 'Patient·e'), ('courageux', 'Courageux·se'), ('prudent', 'Prudent·e'), ('confiant', 'Confiant·e'), ('calme', 'Calme')], default='curieux', help_text="Première qualité choisie par l'élève (affichée en badge)", max_length=20),
        ),
        migrations.AddField(
            model_name='cuber',
            name='quality_2',
            field=models.CharField(choices=[('curieux', 'Curieux·se'), ('intelligent', 'Intelligent·e'), ('rapide', 'Rapide'), ('determine', 'Déterminé·e'), ('perseverant', 'Persévérant·e'), ('concentre', 'Concentré·e'), ('gentil', 'Gentil·le'), ('aidant', 'Aidant·e'), ('creatif', 'Créatif·ve'), ('joyeux', 'Joyeux·se'), ('patient', 'Patient·e'), ('courageux', 'Courageux·se'), ('prudent', 'Prudent·e'), ('confiant', 'Confiant·e'), ('calme', 'Calme')], default='perseverant', help_text="Deuxième qualité choisie par l'élève (affichée en badge)", max_length=20),
        ),
        migrations.AlterField(
            model_name='cuber',
            name='first_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du prénom (ex: 'TO' pour Tommy) — leaders seulement", max_length=2),
        ),
        migrations.AlterField(
            model_name='cuber',
            name='last_name_prefix',
            field=models.CharField(blank=True, help_text="2 premières lettres du nom de famille (ex: 'SM' pour Smith) — leaders seulement", max_length=2),
        ),
    ]
