# Generated by Django 6.0.3 on 2026-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing_users', '0005_alter_cuber_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse courriel')),
                ('role', models.CharField(choices=[('teacher', 'Enseignant'), ('coach', 'Entraîneur'), ('club_leader', 'Animateur de Club'), ('parent', 'Parent Responsable')], max_length=20, verbose_name='Rôle')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('password_hash', models.CharField(max_length=256)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvée')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
            ],
            options={
                'verbose_name': 'Demande Leader',
                'verbose_name_plural': 'Demandes Leader',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
