# Generated by Django 6.0.3 on 2026-03-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CubeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('json_state', models.JSONField()),
                ('json_highlight', models.JSONField(blank=True, null=True)),
                ('algorithm', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('method', models.CharField(choices=[('cubienewbie', 'CubieNewbie'), ('beginner', 'Beginner'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('zz', 'ZZ')], default='beginner', max_length=20)),
                ('hand_orientation', models.CharField(choices=[('right', 'Main Droite'), ('left', 'Main Gauche')], default='right', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('roofpig_setup', models.TextField(blank=True)),
                ('roofpig_colored', models.TextField(blank=True)),
                ('roofpig_flags', models.CharField(blank=True, default='showalg', max_length=200)),
                ('camera_longitude', models.FloatField(default=-25.0, help_text='cubing.js camera horizontal angle. Negative = more front face visible.')),
                ('camera_latitude', models.FloatField(default=22.0, help_text='cubing.js camera vertical angle. Higher = more top-down view.')),
                ('stickering', models.CharField(blank=True, default='full', help_text='cubing.js stickering: full | OLL | PLL | F2L | LL | Cross', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('2x2', '2x2'), ('3x3', '3x3'), ('4x4', '4x4'), ('5x5', '5x5')], max_length=10)),
                ('method', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('algorithm', models.TextField(blank=True)),
                ('setup', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tip', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('camera_longitude', models.FloatField(default=-25.0, help_text='Angle horizontal caméra. Négatif = face avant plus visible.')),
                ('camera_latitude', models.FloatField(default=22.0, help_text='Angle vertical caméra. Plus élevé = vue de dessus.')),
                ('stickering', models.CharField(blank=True, default='full', help_text='cubing.js stickering: full | OLL | PLL | F2L | LL | Cross', max_length=30)),
            ],
            options={
                'verbose_name': 'Puzzle Case',
                'verbose_name_plural': 'Puzzle Cases',
                'ordering': ['puzzle_type', 'method', 'category', 'step_number'],
                'unique_together': {('puzzle_type', 'method', 'category', 'step_number')},
            },
        ),
    ]
