# Generated by Django 6.0.3 on 2026-03-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubestate',
            name='method',
            field=models.CharField(choices=[('cubienewbie', 'CubieNewbie'), ('beginner', 'Beginner'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('reduction-4x4', 'Réduction 4×4'), ('reduction-5x5', 'Réduction 5×5')], default='beginner', max_length=20),
        ),
    ]
