# Generated by Django 6.0.3 on 2026-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_alter_cubestate_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PuzzleCase',
        ),
        migrations.AlterModelOptions(
            name='cubestate',
            options={'ordering': ['method', 'category', 'step_number']},
        ),
        migrations.RenameField(
            model_name='cubestate',
            old_name='roofpig_colored',
            new_name='colored',
        ),
        migrations.RenameField(
            model_name='cubestate',
            old_name='roofpig_flags',
            new_name='flags',
        ),
        migrations.RenameField(
            model_name='cubestate',
            old_name='roofpig_setup',
            new_name='setup',
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='camera_latitude',
            field=models.FloatField(default=22.0, help_text='Vertical camera angle. Higher = more top-down view.'),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='camera_longitude',
            field=models.FloatField(default=-25.0, help_text='Horizontal camera angle. Negative = more front face visible.'),
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='method',
            field=models.CharField(choices=[('cubienewbie', 'CubieNewbie'), ('beginner', 'Beginner'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('zz', 'ZZ'), ('reduction-4x4', 'Réduction 4×4'), ('reduction-5x5', 'Réduction 5×5')], default='beginner', max_length=20),
        ),
    ]
