# Generated by Django 6.0.3 on 2026-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0005_alter_cubestate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubestate',
            name='flags',
        ),
        migrations.AlterField(
            model_name='cubestate',
            name='method',
            field=models.CharField(choices=[('cubienewbie', 'CubieNewbie'), ('cubiecurieux', 'CubieCurieux'), ('cfop', 'CFOP'), ('roux', 'Roux'), ('zz', 'ZZ'), ('reduction-4x4', 'Réduction 4×4'), ('reduction-5x5', 'Réduction 5×5')], default='beginner', max_length=20),
        ),
    ]
