# Generated by Django 6.0.3 on 2026-03-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cubing_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('notation', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField(default=6, verbose_name='Répétitions')),
                ('difficulty', models.CharField(choices=[('apprenti', 'Apprenti Cubi'), ('confirme', 'Cubiste Confirmé'), ('speedcube', 'Speedcubiste'), ('maitre', 'Maître Cubi')], max_length=20, verbose_name='Niveau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Algorithme',
                'verbose_name_plural': 'Algorithmes',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CuberProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time_ms', models.IntegerField(verbose_name='Meilleur temps (ms)')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Tentatives totales')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='Dernière pratique')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.algorithm')),
                ('cuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_progress', to='cubing_users.cuber')),
            ],
            options={
                'verbose_name': 'Progrès Cuber',
                'verbose_name_plural': 'Progrès Cubers',
                'unique_together': {('cuber', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='LeaderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time_ms', models.IntegerField(verbose_name='Meilleur temps (ms)')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Tentatives totales')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='Dernière pratique')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.algorithm')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_progress', to='cubing_users.leader')),
            ],
            options={
                'verbose_name': 'Progrès Leader',
                'verbose_name_plural': 'Progrès Leaders',
                'unique_together': {('leader', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Clé de session pour utilisateurs anonymes', max_length=100, null=True)),
                ('time_ms', models.IntegerField(verbose_name='Temps (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.algorithm')),
                ('cuber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='cubing_users.cuber')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='cubing_users.leader')),
            ],
            options={
                'verbose_name': "Session d'entraînement",
                'verbose_name_plural': "Sessions d'entraînement",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cuber', 'algorithm', '-created_at'], name='training_tr_cuber_i_516fcb_idx'), models.Index(fields=['leader', 'algorithm', '-created_at'], name='training_tr_leader__1dbb22_idx'), models.Index(fields=['session_key', 'algorithm', '-created_at'], name='training_tr_session_d45047_idx')],
            },
        ),
    ]
