# Generated by Django 6.0.3 on 2026-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='difficulty',
            field=models.CharField(choices=[('apprenti', 'Cubie Newbie'), ('confirme', 'Cubiste Confirmé'), ('speedcube', 'Speedcubiste'), ('maitre', 'Maître Cubi')], max_length=20, verbose_name='Niveau'),
        ),
    ]
