# Generated by Django 6.0.3 on 2026-07-01 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cubing_users', '0006_leaderrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji affiché sur le foulard, ex: 🏆', max_length=10)),
                ('family', models.CharField(choices=[('fondations', 'Fondations (Cubie-Newbie)'), ('f2l', 'F2L'), ('oll', 'OLL'), ('pll', 'PLL'), ('avance', 'Avancé'), ('meta', 'Méta'), ('brevet', 'Brevet (regroupement)')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Ce que le cubeur voit: à quoi sert cet écusson')),
                ('criteria_description', models.TextField(blank=True, help_text='Ce que le leader voit lors de la validation: comment vérifier')),
                ('requires_auto_track', models.BooleanField(default=False, help_text='Débloqué en partie par le minuteur / la pratique enregistrée')),
                ('requires_quiz', models.BooleanField(default=False, help_text='Débloqué en partie par un mini-quiz réussi')),
                ('requires_leader_validation', models.BooleanField(default=True, help_text="Un leader doit approuver avant que l'écusson soit officiellement débloqué")),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('is_brevet', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True, help_text='Décoche pour cacher temporairement un écusson en construction')),
                ('requires_badges', models.ManyToManyField(blank=True, help_text='Pour les brevets: écussons qui doivent tous être débloqués', related_name='required_for', to='badges.badge')),
            ],
            options={
                'ordering': ['family', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CuberBadge',
            fields=[
                ('cuberbadge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_track_complete', models.BooleanField(default=False)),
                ('quiz_complete', models.BooleanField(default=False)),
                ('requested_date', models.DateTimeField(blank=True, help_text="Date à laquelle auto-track + quiz ont été complétés (entrée en file d'attente)", null=True)),
                ('validated_date', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuber_progress', to='badges.badge')),
                ('cuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='cubing_users.cuber')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_validated', to='cubing_users.leader')),
            ],
            options={
                'ordering': ['-requested_date'],
                'unique_together': {('cuber', 'badge')},
            },
        ),
    ]
