# Generated by Django 6.0.3 on 2026-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='has_svg_icon',
            field=models.BooleanField(default=False, help_text='Coche une fois que badges/static/badges/icons/{slug}.svg existe. Suit la même convention que les avatars (fichier statique, pas stocké en DB).'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text="Emoji de secours, affiché tant que le SVG n'existe pas. Ex: 🏆", max_length=10),
        ),
    ]
