# Generated by Django 5.1.7 on 2026-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badge_has_svg_icon_alter_badge_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='has_svg_icon',
        ),
        migrations.AddField(
            model_name='badge',
            name='has_custom_icon',
            field=models.BooleanField(default=False, help_text="Coche une fois que badges/static/badges/icons/{slug}.png existe. Icônes composées dans Inkscape à partir d'un rendu CubeState + d'une forme d'écusson."),
        ),
    ]
