# Generated by Django 6.0.3 on 2026-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_remove_badge_has_svg_icon_badge_has_custom_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='family',
            field=models.CharField(choices=[('cubie-newbie', 'Cubie-Newbie'), ('curieux', 'Cubie-Curieux'), ('f2l', 'F2L'), ('oll', 'OLL'), ('pll', 'PLL'), ('avance', 'Avancé'), ('meta', 'Méta'), ('brevet', 'Brevet (regroupement)')], max_length=20),
        ),
    ]
