# Generated by Django 6.0.3 on 2026-07-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_badge_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='learn_url_kwargs',
            field=models.JSONField(blank=True, default=dict, help_text="Kwargs pour reverse(), si l'URL en a besoin (ex: {'slug': 'f2l-05'})."),
        ),
        migrations.AddField(
            model_name='badge',
            name='learn_url_name',
            field=models.CharField(blank=True, help_text="Nom de l'URL Django vers la page qui explique cette mission/cet algorithme (ex: 'main:cubienewbie_daisy'). Laisser vide si aucune page dédiée n'existe encore.", max_length=100),
        ),
    ]
